services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: qa_rag_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qa_rag_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: qa_rag_redis
    ports:
      - "6379:6379"   

  ollama:
    image: ollama/ollama
    container_name: qa_rag_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  
  backend:
    build: ./backend
    container_name: qa_rag_backend
    depends_on:
      - postgres
      - redis
      - ollama

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/qa_rag_app
      REDIS_URL: redis://localhost:6379/0
      OLLAMA_URL: http://ollama:11434
    
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: qa_rag_frontend
    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app

volumes:

  postgres_data:
  ollama_data: