"""add transcript segments

Revision ID: 33035d79b53e
Revises: 5403071bd53e
Create Date: 2026-05-06 18:25:55.902980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33035d79b53e'
down_revision: Union[str, Sequence[str], None] = '5403071bd53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=False, server_default='pdf'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
