"""add embeddings to chunks

Revision ID: 5403071bd53e
Revises: 746e561e0459
Create Date: 2026-05-06 16:07:47.013062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Need to add this - migration file itself not supporting pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '5403071bd53e'
down_revision: Union[str, Sequence[str], None] = '746e561e0459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
