"""add embeddings to transcript segments

Revision ID: a007333bc6b7
Revises: 1d538e1d1ad4
Create Date: 2026-05-06 18:56:49.960795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'a007333bc6b7'
down_revision: Union[str, Sequence[str], None] = '1d538e1d1ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_segments', sa.Column('embedding', Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_segments', 'embedding')
    # ### end Alembic commands ###
